# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/daniel/Documents/ctm_openday/Vivado/matrix_mult/matrix_mult.srcs/sources_1/bd/design_1/ip/design_1_mmult_wrapper_0_0/design_1_mmult_wrapper_0_0.xci
# IP: The module: 'design_1_mmult_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daniel/Documents/ctm_openday/Vivado/matrix_mult/matrix_mult.gen/sources_1/bd/design_1/ip/design_1_mmult_wrapper_0_0/constraints/mmult_wrapper_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mmult_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/daniel/Documents/ctm_openday/Vivado/matrix_mult/matrix_mult.srcs/sources_1/bd/design_1/ip/design_1_mmult_wrapper_0_0/design_1_mmult_wrapper_0_0.xci
# IP: The module: 'design_1_mmult_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daniel/Documents/ctm_openday/Vivado/matrix_mult/matrix_mult.gen/sources_1/bd/design_1/ip/design_1_mmult_wrapper_0_0/constraints/mmult_wrapper_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_mmult_wrapper_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
